//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="https://java.sun.com/xml/jaxb">https://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2015.11.05 at 05:47:27 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.osgi.org/xmlns/blueprint/v1.0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.springframework.ide.eclipse.osgi.blueprint.internal.jaxb;
