//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 05:47:27 PM CET 
//

package org.springframework.ide.eclipse.osgi.blueprint.internal.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

/**
 * 
 * 
 * The Tkey type defines the element types that are permitted for Map key
 * situations. These can be any of the "value" types other than the
 * <null> element.
 * 
 * 
 * 
 * <p>
 * Java class for Tkey complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Tkey">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.osgi.org/xmlns/blueprint/v1.0.0}GnonNullValue"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tkey", propOrder = { "service", "referenceList", "bean", "reference", "targetRef", "any", "idref",
		"value", "list", "set", "map", "array", "props" })
public class Tkey {

	protected TinlinedService service;
	@XmlElement(name = "reference-list")
	protected TinlinedReferenceList referenceList;
	protected TinlinedBean bean;
	protected TinlinedReference reference;
	@XmlElement(name = "ref")
	protected Tref targetRef;
	@XmlAnyElement(lax = true)
	protected Object any;
	protected Tref idref;
	protected Tvalue value;
	protected Tcollection list;
	protected Tcollection set;
	protected Tmap map;
	protected Tcollection array;
	protected Tprops props;

	/**
	 * Gets the value of the service property.
	 * 
	 * @return possible object is {@link TinlinedService }
	 * 
	 */
	public TinlinedService getService() {
		return service;
	}

	/**
	 * Sets the value of the service property.
	 * 
	 * @param value
	 *            allowed object is {@link TinlinedService }
	 * 
	 */
	public void setService(TinlinedService value) {
		this.service = value;
	}

	/**
	 * Gets the value of the referenceList property.
	 * 
	 * @return possible object is {@link TinlinedReferenceList }
	 * 
	 */
	public TinlinedReferenceList getReferenceList() {
		return referenceList;
	}

	/**
	 * Sets the value of the referenceList property.
	 * 
	 * @param value
	 *            allowed object is {@link TinlinedReferenceList }
	 * 
	 */
	public void setReferenceList(TinlinedReferenceList value) {
		this.referenceList = value;
	}

	/**
	 * Gets the value of the bean property.
	 * 
	 * @return possible object is {@link TinlinedBean }
	 * 
	 */
	public TinlinedBean getBean() {
		return bean;
	}

	/**
	 * Sets the value of the bean property.
	 * 
	 * @param value
	 *            allowed object is {@link TinlinedBean }
	 * 
	 */
	public void setBean(TinlinedBean value) {
		this.bean = value;
	}

	/**
	 * Gets the value of the reference property.
	 * 
	 * @return possible object is {@link TinlinedReference }
	 * 
	 */
	public TinlinedReference getReference() {
		return reference;
	}

	/**
	 * Sets the value of the reference property.
	 * 
	 * @param value
	 *            allowed object is {@link TinlinedReference }
	 * 
	 */
	public void setReference(TinlinedReference value) {
		this.reference = value;
	}

	/**
	 * Gets the value of the targetRef property.
	 * 
	 * @return possible object is {@link Tref }
	 * 
	 */
	public Tref getTargetRef() {
		return targetRef;
	}

	/**
	 * Sets the value of the targetRef property.
	 * 
	 * @param value
	 *            allowed object is {@link Tref }
	 * 
	 */
	public void setTargetRef(Tref value) {
		this.targetRef = value;
	}

	/**
	 * Gets the value of the any property.
	 * 
	 * @return possible object is {@link Element } {@link Object }
	 * 
	 */
	public Object getAny() {
		return any;
	}

	/**
	 * Sets the value of the any property.
	 * 
	 * @param value
	 *            allowed object is {@link Element } {@link Object }
	 * 
	 */
	public void setAny(Object value) {
		this.any = value;
	}

	/**
	 * Gets the value of the idref property.
	 * 
	 * @return possible object is {@link Tref }
	 * 
	 */
	public Tref getIdref() {
		return idref;
	}

	/**
	 * Sets the value of the idref property.
	 * 
	 * @param value
	 *            allowed object is {@link Tref }
	 * 
	 */
	public void setIdref(Tref value) {
		this.idref = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link Tvalue }
	 * 
	 */
	public Tvalue getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link Tvalue }
	 * 
	 */
	public void setValue(Tvalue value) {
		this.value = value;
	}

	/**
	 * Gets the value of the list property.
	 * 
	 * @return possible object is {@link Tcollection }
	 * 
	 */
	public Tcollection getList() {
		return list;
	}

	/**
	 * Sets the value of the list property.
	 * 
	 * @param value
	 *            allowed object is {@link Tcollection }
	 * 
	 */
	public void setList(Tcollection value) {
		this.list = value;
	}

	/**
	 * Gets the value of the set property.
	 * 
	 * @return possible object is {@link Tcollection }
	 * 
	 */
	public Tcollection getSet() {
		return set;
	}

	/**
	 * Sets the value of the set property.
	 * 
	 * @param value
	 *            allowed object is {@link Tcollection }
	 * 
	 */
	public void setSet(Tcollection value) {
		this.set = value;
	}

	/**
	 * Gets the value of the map property.
	 * 
	 * @return possible object is {@link Tmap }
	 * 
	 */
	public Tmap getMap() {
		return map;
	}

	/**
	 * Sets the value of the map property.
	 * 
	 * @param value
	 *            allowed object is {@link Tmap }
	 * 
	 */
	public void setMap(Tmap value) {
		this.map = value;
	}

	/**
	 * Gets the value of the array property.
	 * 
	 * @return possible object is {@link Tcollection }
	 * 
	 */
	public Tcollection getArray() {
		return array;
	}

	/**
	 * Sets the value of the array property.
	 * 
	 * @param value
	 *            allowed object is {@link Tcollection }
	 * 
	 */
	public void setArray(Tcollection value) {
		this.array = value;
	}

	/**
	 * Gets the value of the props property.
	 * 
	 * @return possible object is {@link Tprops }
	 * 
	 */
	public Tprops getProps() {
		return props;
	}

	/**
	 * Sets the value of the props property.
	 * 
	 * @param value
	 *            allowed object is {@link Tprops }
	 * 
	 */
	public void setProps(Tprops value) {
		this.props = value;
	}

}
