//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 05:47:27 PM CET 
//

package org.springframework.ide.eclipse.osgi.blueprint.internal.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * 
 * Tmap is the base type used for <map> elements. A map may have a default value
 * type specified, so it inherits from the TtypeCollection type. A key type can
 * also be specified, and the map members are created from the entry elements,
 * which require a key/value pair.
 * 
 * 
 * 
 * <p>
 * Java class for Tmap complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Tmap">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.osgi.org/xmlns/blueprint/v1.0.0}TtypedCollection">
 *       &lt;sequence>
 *         &lt;element name="entry" type="{http://www.osgi.org/xmlns/blueprint/v1.0.0}TmapEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key-type" type="{http://www.osgi.org/xmlns/blueprint/v1.0.0}Ttype" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tmap", propOrder = { "entry" })
public class Tmap extends TtypedCollection {

	protected List<TmapEntry> entry;
	@XmlAttribute(name = "key-type")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String keyType;

	/**
	 * Gets the value of the entry property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the entry property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEntry().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TmapEntry
	 * }
	 * 
	 * 
	 */
	public List<TmapEntry> getEntry() {
		if (entry == null) {
			entry = new ArrayList<TmapEntry>();
		}
		return this.entry;
	}

	/**
	 * Gets the value of the keyType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getKeyType() {
		return keyType;
	}

	/**
	 * Sets the value of the keyType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setKeyType(String value) {
		this.keyType = value;
	}

}
