//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="https://java.sun.com/xml/jaxb">https://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 05:47:27 PM CET 
//

package org.springframework.ide.eclipse.osgi.blueprint.internal.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

/**
 * 
 * 
 * The Treference-list builds in the characteristics of the TserviceReference
 * type to define characteristics of the <reference-list>. This adds in the
 * characteristics that only apply to collections of references (e.g.,
 * member-type).
 * 
 * 
 * 
 * <p>
 * Java class for Treference-list complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Treference-list">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.osgi.org/xmlns/blueprint/v1.0.0}TserviceReference">
 *       &lt;sequence>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="member-type" type="{http://www.osgi.org/xmlns/blueprint/v1.0.0}Tservice-use" default="service-object" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Treference-list", propOrder = { "any" })
@XmlSeeAlso({ TinlinedReferenceList.class })
public class TreferenceList extends TserviceReference {

	@XmlAnyElement(lax = true)
	protected List<Object> any;
	@XmlAttribute(name = "member-type")
	protected TserviceUse memberType;

	/**
	 * Gets the value of the any property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the any property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAny().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Element }
	 * {@link Object }
	 * 
	 * 
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	/**
	 * Gets the value of the memberType property.
	 * 
	 * @return possible object is {@link TserviceUse }
	 * 
	 */
	public TserviceUse getMemberType() {
		if (memberType == null) {
			return TserviceUse.SERVICE_OBJECT;
		} else {
			return memberType;
		}
	}

	/**
	 * Sets the value of the memberType property.
	 * 
	 * @param value
	 *            allowed object is {@link TserviceUse }
	 * 
	 */
	public void setMemberType(TserviceUse value) {
		this.memberType = value;
	}

}
